### ISSUE TITLE
Parse Error on CreateInvoiceAsync

### ISSUE THREAD

**Issue by Kukks** [MetacoSA/NBitpayClient#12]
getting a parsing error when connecting to https://test2-btc-ltc.forkbitpay.ninja and attempting to create an invoice

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at NBitpayClient.Bitpay.<ParseResponse>d__41`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NBitpayClient.Bitpay.<CreateInvoiceAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
```

**Comment by Kukks** [comment]
Response when it does a post to btcpayserver:
```
{StatusCode: 500, ReasonPhrase: 'Internal Server Error', Version: 1.1, Content: System.Net.Http.NoWriteNoSeekStreamContent, Headers:
{
  Server: nginx
  Date: Sat, 26 May 2018 12:34:15 GMT
  Connection: keep-alive
  Strict-Transport-Security: max-age=31536000
  Content-Length: 0
}}
```

**Comment by Kukks** [comment]
Tried on a different instance of btcpay and it works

**Comment by NicolasDorier** [comment]
@Kukks you need to update NBitpayClient and BTCPay. I messed up the minerFees.
