### ISSUE TITLE
ETH way too big to be deserialized.

### ISSUE THREAD

**Issue by MrTarantula** [MetacoSA/NBitpayClient#24]
You may need to switch to a different type for ETH totals. The number exceeds Int64.
 
```
System.OverflowException: Value was either too large or too small for an Int64.
Generated: Tue, 10 Dec 2019 15:48:18 GMT
Newtonsoft.Json.JsonSerializationException: Error converting value 13755283000000000000 to type 'System.Int64'. Path 'paymentSubtotals.ETH', line 35, position 31. ---> System.InvalidOperationException: Can not convert from BigInteger to System.Int64. ---> System.OverflowException: Value was either too large or too small for an Int64.
   at System.Numerics.BigInteger.op_Explicit(BigInteger value)
   at Newtonsoft.Json.Utilities.ConvertUtils.FromBigInteger(BigInteger i, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Utilities.ConvertUtils.FromBigInteger(BigInteger i, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NBitpayClient.Bitpay.ParseResponse[T](HttpResponseMessage response)
   at NBitpayClient.Bitpay.CreateInvoiceAsync(Invoice invoice, Facade facade)
   at NBitpayClient.Bitpay.CreateInvoice(Invoice invoice, Facade facade)
  [REDACTED]
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()
```

**Comment by NicolasDorier** [comment]
This library will not support ETH, probably the official bitpay library does.

**Comment by MrTarantula** [comment]
While it does not support ETH, the ETH values are still [sent as part of an invoice](https://bitpay.com/api/#rest-api-resources-invoices-fetch-an-invoice-by-id):

![image](https://user-images.githubusercontent.com/11617455/70807978-4f354080-1d84-11ea-825d-c1c8d449429c.png)

Regardless of whether they are used, the library still attempts to map to a [`Dictionary<string, long>`](https://github.com/MetacoSA/NBitpayClient/blob/c0c0f81dc89162981169f81770d8776e26add707/NBitpayClient/Invoice.cs#L383).

**Comment by NicolasDorier** [comment]
@MrTarantula you are right, should be `decimal`. Can you make a PR, will bump it.

**Comment by kspearrin** [comment]
@NicolasDorier This issue is also present for PAX paymentSubtotals:

```
Error converting value 10000000000000000000 to type 'System.Int64'. Path 'paymentSubtotals.PAX', line 34, position 31.

Exception

Message:
Error converting value 10000000000000000000 to type 'System.Int64'. Path 'paymentSubtotals.PAX', line 34, position 31.

Stack Trace:
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)

   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)

   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)

   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)

   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)

   at NBitpayClient.Bitpay.ParseResponse[T](HttpResponseMessage response)

   at NBitpayClient.Bitpay.CreateInvoiceAsync(Invoice invoice, Facade facade)

   at Bit.Api.Controllers.MiscController.PostBitPayInvoice(BitPayInvoiceRequestModel model) in C:\Projects\bitwarden\server\src\Api\Controllers\MiscController.cs:line 53

   at lambda_method(Closure , Object )

   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()

   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)

   at System.Threading.Tasks.ValueTask`1.get_Result()

   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()

   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()

   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)

   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)

   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()

   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()

=== Inner Exception ===

Message:
Can not convert from BigInteger to System.Int64.

Stack Trace String:
   at Newtonsoft.Json.Utilities.ConvertUtils.FromBigInteger(BigInteger i, Type targetType)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)

=== Inner Exception ===

Message:
Value was either too large or too small for an Int64.

Stack Trace String:
   at System.Numerics.BigInteger.op_Explicit(BigInteger value)

   at Newtonsoft.Json.Utilities.ConvertUtils.FromBigInteger(BigInteger i, Type targetType)
```

**Comment by NicolasDorier** [comment]
@kspearrin the problem is that "10000000000000000000" is too big of a number.

JSON is based on javascript, and javascript number max is `2^53 - 1`. So your case will never work because of plain old javascript limitation. (note that there is maximum 21 million bitcoin for a similar reason but about float precision)

@MrTarantula case should work though, it should be decimal.

**Comment by MrTarantula** [comment]
I'll submit a PR soon. Should I bump the version or will you take care of that?

**Comment by NicolasDorier** [comment]
@MrTarantula whichever
